#apiVersion: networking.k8s.io/v1
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
      name: ingress-service
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: client-cluster-ip-service
          servicePort: 3000
          #service:
           # name: client-cluster-ip-service
            #port: 
             # number: 3000
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          serviceName: server-cluster-ip-service
          servicePort: 5000
          #service:
           # name: server-cluster-ip-service
            #port: 
             # number: 5000


